### ISSUE TITLE
RN 0.72 support?

### ISSUE THREAD

**Issue by marcshilling** [starters-dev/rnn-with-expo#4]
Any way to get RNN working with RN 0.72 yet?

**Comment by kanzitelli** [comment]
hey @marcshilling! That would be nice to have ofc but due to lack of personal time and many changes to RN ecosystem like new arch, etc., much more time will be needed to dive into Expo + RNN integration. That's why I've moved mostly to Expo + React Navigation + Navio (like RNN API for navigation)

**Comment by marcshilling** [comment]
Thanks, I actually managed to get it working! If anyone else is reading, nothing special really just need to leave most of the AppDelegate/MainApplication code the same as RNN docs recommend (contrary to what the upgrade helper says)
